### ISSUE TITLE
Qual a estrutura no html?

### ISSUE THREAD

**Issue by ivanaugustobd** [cssbrasil/animated-icons#4]
Como usaremos os ícones na prática? Pensei em duas variantes:

Uma para ícones que vão de um forma à outra, ficando `ai-foo-to-bar`
```html
<label class="ai ai-foo-to-bar">
  <input type="checkbox"> <!-- poderia ser radio também mas seria opcional, já que pode ser feito um simples toggle de class "active" no wrapper -->
  <span></span><span></span><span></span>
  <!-- usando pseudo-elementos (before/after) o CSS fica bem verboso, por isso esse trio de <span> -->
</label>
```

E outra para ícones simples (como radio e checkbox), ficando apenas `ai-foo`:
```html
<input type="checkbox" id="foo" class="ai-trigger">
<label class="ai ai-foo" for="foo"></label>
```

Mas estou achando meio verboso; fora que duas variantes pode não ser algo muito intuitivo.. :thinking:

**Comment by ivanaugustobd** [comment]
Outra maneira seria criar componentes (tipo Vue/Polymer) pra abstrair isso, daí ficaria mais simples ainda. Algo como:
```html
<!-- ícones "simples" e os demais seriam chamados da mesma forma -->
<animated-icon type="checkbox"></animated-icon>
<animated-icon type="hamburger-to-x"></animated-icon>
```

Mas teríamos que ter cuidado pra que isso fosse apenas um adicional (provavelmente repos/packages à parte), sem violar a proposta de ser agnóstico..

**Comment by emanuelgsouza** [comment]
Boa. Eu não achei verboso. Achei necessário. Acho interessante a gente tentar manter os ícones os mais simples do ponto de vista do HTML.

**Comment by ricardomirannda** [comment]
Achei interessante poder criar componentes (tipo Vue/Polymer), código simples e objetivo:

<animated-icon type="checkbox"></animated-icon>
<animated-icon type="hamburger-to-x"></animated-icon>

**Comment by ricardomirannda** [comment]
<animated-icon type="checkbox"></animated-icon>
<animated-icon type="hamburger-to-x"></animated-icon>

**Comment by ricardomirannda** [comment]
Achei interessante poder criar componentes (tipo Vue/Polymer), código simples e objetivo.

**Comment by ivanaugustobd** [comment]
Não se preocupe @devigor, Vue/Polymer foram só os primeiros que vieram à mente, provavelmente viríamos a incluir o React também :stuck_out_tongue_winking_eye:

**Comment by wilcorrea** [comment]
@ivanaugustobd no dia-a-dia é muito melhor tem um CSS verboso, minificado do que escrever 3 spans para montar um markup
```html
<label class="ai ai-foo-to-bar">
  <input type="checkbox">
</label>
```
Deveria ser o suficiente IMHO : )

**Comment by ivanaugustobd** [comment]
Esse **com certeza seria o cenário ideal**, mas _eu_ não consigo ver o CSS disso _ainda_ (usando o que sei _atualmente_ gastaria no mínimo um `<span>` para caras como o `.ai-hamburger-to-whatever`) :thinking: 

Inclusive, enquanto procurava por pacotes similares me deparei com este [animated-menu-icon](https://www.npmjs.com/package/animated-menu-icon) (até o nome é parecido rsrs) que usa exatamente esse conceito, baseado [nesse pen](https://codepen.io/designcouch/pen/Atyop) (que tem mais likes que os meus tem views rsrs)

Mas vou tentar pensar em algo.. Na pior das hipóteses deixamos essa simplificação de markup para uma release futura :sweat_smile:

**Comment by wilcorrea** [comment]
Entendi @ivanaugustobd

**Comment by ivanaugustobd** [comment]
Então é isso, inicialmente usaremos o par de estruturas sugeridos acima e, se possível, futuramente simplificamos ela. Quanto ao uso de web components, vamos pensar numa forma a qual este pacote possa ser reaproveitado como dependência em novos pacotes (algo como `animated-icons-{vue,react,polymer`)
