### ISSUE TITLE
Build tool a ser usada

### ISSUE THREAD

**Issue by ivanaugustobd** [cssbrasil/animated-icons#6]
O que usaremos para compilar o código #2? Pessoalmente sugiro o [Gulp](https://gulpjs.com), por ser extremamente simples e conhecido; daí deixamos atalho pras tasks como scripts npm no package.json

**Comment by devigor** [comment]
Gulp sem dúvida!!! Fácil escrita de código e menos complicado do que um Grunt da vida

**Comment by ivanaugustobd** [comment]
Grunt é o de menos, imagina se fosse o Webpack 😛

**Comment by ivanaugustobd** [comment]
:1st_place_medal: Gulp
